### ISSUE TITLE
Error while parsing the movies schema

### ISSUE THREAD

**Issue by limiaspasdaniel** [graknlabs/sample-datasets#26]
A structural validation error has occurred. Please correct the [`2`] errors found. 
RoleType ['parent'] does not have exactly one has-role connection to any Relation Type. 
RoleType ['child'] does not have exactly one has-role connection to any Relation Type. 

Above happens when loading the schema into the newest version of Grakn.

**Comment by alexandraorth** [comment]
Hey Daniel! Could you let us know what version you are using? We're looking into this now.

**Comment by limiaspasdaniel** [comment]
@alexandraorth According to the version number under the configuration section in the dashboard: 0.9.0 but I'm not sure if that's correct version number. Anyways, to be clear,  I downloaded Grakn yesterday from [](https://grakn.ai/download/latest). Btw the error happened when loading the movies schema. I forgot to mention it.

Thank you

**Comment by alexandraorth** [comment]
I've just tried downloading the latest Grakn and loaded the movie ontology without any trouble, so we think it's possible that there might be other conflicting data in your graph.

Can you try either cleaning the graph and then re-loading or just loading into a different keyspace?

To clean (we recommend stopping, cleaning and then starting):
```
bin/grakn.sh stop
bin/grakn.sh clean
bin/grakn.sh start
```

To load into a different keyspace:
```
bin/graql.sh -f path/to/movies/schema.gql -k movies
```
